server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: swagger-ui
          uri: https://webjars.org
          predicates:
            - Path=/swagger-ui.html
          filters:
            - RewritePath=/swagger-ui.html, /swagger-ui/index.html
            - SetPath=/
        - id: swagger-resources
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger-resources/**
        - id: api-docs
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs
        - id: webjars
          uri: https://webjars.org
          predicates:
            - Path=/webjars/**
          filters:
            - RewritePath=/webjars/(?<path>.*), /org/webjars/swagger-ui/2.5.0/$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /swagger-resources/configuration/ui
  api-docs:
    path: /v3/api-docs
  swagger-resources:
    path: /swagger-resources

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always