server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: storage-route
          uri: http://storage-node:8081
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1

  main:
    web-application-type: reactive

  springdoc:
    swagger-ui:
      path: /docs-api/swagger-ui.html
      urls:
        - name: Gateway API
        - name: Read Node API
          url: http://read-node:8083/v3/api-docs
        - name: Storage Node API
          url: http://storage-node:8081/v3/api-docs
      config-url: /docs-api/swagger-resources/configuration/ui

    api-docs:
      path: /v3/api-docs

    swagger-resources:
      path: /swagger-resources

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always