server:
  port: 8081

spring:
  application:
    name: storage-node
  datasource:
    url: jdbc:mysql://localhost:3307/kv_backup
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true